export default [{
        label: "通用图标",
        list: [
            "el-icon-plus",
            "el-icon-remove",
            "el-icon-success",
            "el-icon-warning",
            "el-icon-error",
            "el-icon-zoom-in",
            "el-icon-zoom-out",
            "el-icon-download",
            "el-icon-camera-solid",
            "el-icon-plus",
            "el-icon-remove",
            "el-icon-success",
            "el-icon-warning",
            "el-icon-error",
            "el-icon-zoom-in",
            "el-icon-zoom-out",
            "el-icon-download",
            "el-icon-camera-solid", "el-icon-plus",
            "el-icon-remove",
            "el-icon-success",
            "el-icon-warning",
            "el-icon-error",
            "el-icon-zoom-in",
            "el-icon-zoom-out",
            "el-icon-download",
            "el-icon-camera-solid",
        ]
    },
    {
        label: "系统图标",
        list: [
            "el-icon-delete-solid",
            "el-icon-delete",
            "el-icon-s-tools",
            "el-icon-setting",
            "el-icon-user-solid",
            "el-icon-phone",
            "el-icon-more",
            "el-icon-star-on",
            "el-icon-s-goods",
            "el-icon-delete-solid",
            "el-icon-delete",
            "el-icon-s-tools",
            "el-icon-setting",
            "el-icon-user-solid",
            "el-icon-phone",
            "el-icon-more",
            "el-icon-star-on",
            "el-icon-s-goods",
            "el-icon-delete-solid",
            "el-icon-delete",
            "el-icon-s-tools",
            "el-icon-setting",
            "el-icon-user-solid",
            "el-icon-phone",
            "el-icon-more",
            "el-icon-star-on",
            "el-icon-s-goods",
        ]
    }
]